import { cn } from "@/lib/utils";
import "./globals.css";
import Navbar from "@/components/fragments/navigations/Navbar";
import { AOSInit } from "@/lib/animation/aos";
import { Toaster } from "@/components/ui/toaster";
import { fontHeading, fontBody } from "@/fonts/fonts";
import ButtonSlideUp from "@/components/core/ButtonSlideUp";
import ParticlesComponent from "@/components/core/Particles";
export const metadata = {
  title: "Syafira & Ibnu",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  }
};
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <AOSInit />
      <body
        className={`${cn(
          "antialiased",
          fontHeading.variable,
          fontBody.variable
        )} overflow-x-hidden bg-cream-100`}
      >
        <ParticlesComponent />
        <Navbar />
        {children}
        <ButtonSlideUp />

        <Toaster />
      </body>
    </html>
  );
}
